cargo-features = ["resolver"]

[workspace]
members = [
	"auction",
	"authority",
	"benchmarking",
	"currencies",
	"gradually-update",
	"oracle",
	"oracle/rpc",
	"oracle/rpc/runtime-api",
	"tokens",
	"traits",
	"utilities",
	"vesting",
	"rewards",
	"nft",
	"xtokens",
	"xcm-support",
	"unknown-tokens",
	"build-script-utils",
]
resolver = "2"

